resources:
  repositories:
    - repository: Module
      type: GitHub
      endpoint: jared-holgate-microsoft-demos
      name: jared-holgate-microsoft-demos/terraform-module-test-module

trigger:
- main

pool: Default

steps:
- checkout: self
- checkout: Module

- script: terraform init
  displayName: 'Terraform Init'

- script: terraform apply -auto-approve
  displayName: 'Terrafrom Apply'
