trigger:
- main

resources:
  repositories:
    - repository: terraform_module
      type: github
      endpoint: jared-holgate-microsoft-demos
      name: jared-holgate-microsoft-demos/terraform-module-test-module

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
  path: s

- checkout: terraform_module
  persistCredentials: true
  path: temp/module

- pwsh: |
    $repository = "$(Build.Repository.Uri)"
    $organisation = $repository -replace '/[^/]+$'
    
    $token = git config --get http.$repository.extraheader

    git config --global http.https://github.com.extraheader $token
  displayName: 'Get Config Pipeline'

- script: terraform init
  displayName: 'Terraform Init'
  env:
    TF_LOG: TRACE

- script: terraform apply -auto-approve
  displayName: 'Terrafrom Apply'
