resources:
  repositories:
    - repository: Module
      type: GitHub
      endpoint: jared-holgate-microsoft-demos
      name: jared-holgate-microsoft-demos/terraform-module-test-module

trigger:
- main

pool: Default

steps:
- checkout: self
  persistCredentials: true
- checkout: Module
  persistCredentials: true
  
- script: git config --list --show-origin
  displayName: 'Get Config Module'
  workingDirectory: terraform-module-test-module

- pwsh: |
    $repository = $(Build.Repository.Uri)
    $organisation = $repository -replace '/[^/]+$'
    $token = git config --get http.$(Build.Repository.Uri).extraheader
    git config http.$organisation.extraheader $token
    type .git\config
  displayName: 'Get Config Pipeline'
  workingDirectory: terraform-module-test-pipeline

- script: terraform init
  displayName: 'Terraform Init'
  workingDirectory: terraform-module-test-pipeline

- script: terraform apply -auto-approve
  displayName: 'Terrafrom Apply'
  workingDirectory: terraform-module-test-pipeline
